image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  before_script:
    - apk add --no-cache git

  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

